# [Info]
site_name: 韬安的个人网站 # 左上角标题
site_url: https://wang-taoan.github.io
site_author: 王韬安
site_description: 韬安的个人网站

# [UI]
theme:
  name: material
  favicon: ./images/favicon.png # 网站图标
  palette:
    - scheme: default # 日间模式
      primary: indigo # 主题颜色indigo red
      accent: amber # 链接等可交互元件的高亮色
      toggle:
        icon: material/brightness-7 # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: indigo #indigo red
      accent: amber
      toggle:
        icon: material/brightness-4
        name: 切换至日间模式  
  features: 
    - content.tooltips
    - navigation.instant # Instant loading
    - navigation.instant.progress # 进度指示器
    - navigation.tracking #Anchor tracking 
    - navigation.tabs # 使用Tab来进行分类，就是顶层的tabs菜单
    - navigation.tabs.sticky # 锁住Tabs，向下划的时候，上面的tabs不会消失
    # - navigation.sections # 对左边菜单栏的优化，加了，文章菜单全部自动展开。不加的话有个收起的按钮
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.indexes # Tab会有一个index.md 而不是在打开Tab时打开第一篇文章
    - navigation.expand # 打开Tab时左侧目录全部展开
    - toc.follow # the sidebar is automatically scrolled so that active anchor is always visible
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - search.share # 搜索中会出现的分享按钮
    - header.autohide # 当用户滚动超过一定阈值时，留出更多的内容空间
    - navigation.footer # previous and next page of the current page的链接
  language: zh # 一些提示性的文字会变成中文
  icon:
    repo: fontawesome/brands/github
    logo: logo-monochrome # logo查询https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/
edit_uri: edit/main/docs # 编辑按钮跳转的链接
## [top-right corner]
repo_url: https://github.com/Wang-Taoan/Wang-Taoan.github.io #右上角跳转的链接
repo_name: Wang-taoan.github.io # 右上角的名字
## [bottom-left corner]
copyright: 2023-2025 王韬安 # 左下角的版权声明
## [bottom-right corner]
extra:
  homepage: https://wang-taoan.github.io/
  social: # icons
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/506537329?spm_id_from=333.337.0.0
      name: Bilibili丨勇敢的湍流  # 鼠标悬浮提示
    - icon: simple/xiaohongshu
      link: https://www.xiaohongshu.com/user/profile/5be67469c6138500017451d4
      name: 小红书丨Santiago  # 鼠标悬浮提示
    - icon: fontawesome/brands/github
      link: https://github.com/Wang-Taoan
      name: Github丨Wang-Taoan

# [Navigtion]
nav:
  - 博客:
    - BLOG/index.md
    - C:
      - 「01」初学C语言: BLOG/C/First-learnC1.md
      - 「02」初学C语言: BLOG/C/First-learnC2.md
      -  不太明白的语法: BLOG/C/ignorantOfSyntax.md
      - 期末复习总结: BLOG/C/C期末复习总结.md
    - JAVA:
      - 入门Java: BLOG/JAVA/begin-java.md
      - 「01」面向对象: BLOG/JAVA/01-object-oriented.md
      - 「02」面向对象: BLOG/JAVA/02-object-oriented.md
      - Java核心技术卷I笔记: BLOG/JAVA/Java-hxj1-notes.md
    - 计算机体系结构:
      - HDL下理解一台Hack计算机: BLOG/ComputerArchitecture/HDL下理解一台Hack计算机.md
      - HDL下理解一个简易的CPU: BLOG/ComputerArchitecture/HDL下理解一个简易的CPU.md
      - HDL下理解一个简易的Memory: BLOG/ComputerArchitecture/HDL下理解一个简易的Memory.md
      - HDL下理解RAM8: BLOG/ComputerArchitecture/HDL下理解RAM8.md
      - 区别RAM和ROM: BLOG/ComputerArchitecture/区分RAM和ROM.md
      - ROM32K的单位换算: BLOG/ComputerArchitecture/ROM32K的单位换算.md
      - Hack汇编语言: BLOG/ComputerArchitecture/Hack汇编语言.md
      - 期末复习: BLOG/ComputerArchitecture/期末复习.md

    - 计算机基础:
      - 汇总: BLOG/ComputerFundamentals/fundamental.md

    - 计算机网络:
      - 网络知识点汇总: BLOG/Network/Summary-of-network.md
      - 期末计算题汇总: BLOG/Network/Summary-of-calculation.md
      - 小林coding网络note: BLOG/Network/xiaolincoding-note.md
      - 什么是VPN: BLOG/Network/What-is-VPN.md

    - Markdown:
      - Markdown文件命名规则: BLOG/Markdown/name-regulation.md
      - Markdown使用语法: BLOG/Markdown/markdown-grammar.md
      #- 文章3:<相对路径>
    - macOS:
      - Homebrew: BLOG/MacOS/Homebrew.md
      - Git: BLOG/MacOS/git.md
      - 环境变量: BLOG/MacOS/环境变量.md
      - 图片格式转换: BLOG/MacOS/mac-imgs.md
      - Tampermonkey: BLOG/MacOS/Tampermonkey.md
    - 生活中的计算机:
      - SSD存储大小怎么小了: BLOG/CsInTheESSAY/SSD-in-ESSAY.md
      - 宽带的实际速度: BLOG/CsInTheESSAY/broadband.md
      - 字节和字符: BLOG/CsInTheESSAY/characters-and-bytes.md
      - HTTP与HTTPS: BLOG/CsInTheESSAY/HTTP-HTTPS.md

    - 其他:
      - 如何下载音乐: BLOG/Other/download-music.md
      - 概率论期末总结: BLOG/Other/概率期末题型总结.md
      #- 文章2:<相对路径>
      #- 文章3:<相对路径>
    #- MacOS
      #- 文章1:<相对路径>
      #- 文章2:<相对路径>
      #- 文章3:<相对路径>
  - 开发:
    - DEVELOPMENT/index.md
    - 开发兴趣: DEVELOPMENT/interests.md
    - 前端:
      - H5: DEVELOPMENT/Front-end/h5.md
      - CSS3: DEVELOPMENT/Front-end/css3.md
      - Vue Notes: DEVELOPMENT/Front-end/Vue2.md
      - element+echarts: DEVELOPMENT/Front-end/elementecharts.md
      - 开发问题记录: DEVELOPMENT/Front-end/recordquestions.md
    - 后端:
      - Spring: DEVELOPMENT/Back-end/Spring.md
      - MySQL: DEVELOPMENT/Back-end/MySQL.md
      - ruoyi-vue: DEVELOPMENT/Back-end/ruoyi.md
      - interface: DEVELOPMENT/Back-end/interface.md
    - App:
      - uni-app: DEVELOPMENT/App/uniapp.md
      - Android: DEVELOPMENT/App/Android.md
    - Git:
      - Git notes: DEVELOPMENT/Git/git.md
  - 规划:
    - PLAN/index.md
    - 学习流:
      - 开发学习推荐: PLAN/Target/Recommend.md
      - 大三上日常学习流: PLAN/Target/202309-Learning.md
      - 大二下日常学习流: PLAN/Target/202303-Learning.md
    
  - 生活:
    - LIKETHINGS/index.md
    - 喜欢的:
      - 喜欢的歌手: LIKETHINGS/Like/Singer.md
      - 喜欢的流行歌: LIKETHINGS/Like/songs.md
      - 喜欢的诗词歌赋: LIKETHINGS/Like/poems.md
    - Coc:
      - Coc 理想的状态: LIKETHINGS/Coc/CocState.md
      - Coc 流派: LIKETHINGS/Coc/CocTroop.md
      - Coc 设置: LIKETHINGS/Coc/CocSetting.md
    - 三国杀:
      - 三国杀 英雄台词: LIKETHINGS/Sgs/三国杀人物台词.md
      - 三国杀 获得道具途径: LIKETHINGS/Sgs/sgsWays.md
    #- LIKE1
      #- 文章1:<相对路径>
      #- 文章2:<相对路径>
      #- 文章3:<相对路径>
   
  - 随笔: 
    - ESSAY/index.md
    - 随笔记:
      - 随笔记 | 前言: ESSAY/Jottings/随笔前言.md
      - 随笔记 | 2409-2411: ESSAY/Jottings/2409-2411.md
      - 随笔记 | 2407-2408: ESSAY/Jottings/2407-2408.md
      - 随笔记 | 2405-2406: ESSAY/Jottings/2405-2406.md 
      - 随笔记 | 2403-2404: ESSAY/Jottings/2403-2404.md
      - 随笔记 | 2401-2402: ESSAY/Jottings/2401-2402.md
      - 随笔记 | 2311-2312: ESSAY/Jottings/2311-2312.md
      - 随笔记 | 2309-2310: ESSAY/Jottings/2309-2310.md
      - 随笔记 | 2307-2308: ESSAY/Jottings/2307-2308.md
      - 随笔记 | 2305-2306: ESSAY/Jottings/2305-2306.md
      - 随笔记 | 2303-2304: ESSAY/Jottings/2303-2304.md
      - 随笔记 | 2301-2302: ESSAY/Jottings/2301-2302.md
      - 随笔记 | 2211-2212: ESSAY/Jottings/2211-2212.md
      #- 文章3:<相对路径>
    - 文章:
      - 25考研回顾: ESSAY/Article/2024kaoyan.md
      - Shall we talk?: ESSAY/Article/Shall-we-talk.md
      - 浮躁时怎么办: ESSAY/Article/Address-Anxiety.md
      - 理想中的女生: ESSAY/Article/Ideal-girl.md
      - 学校自习室选择: ESSAY/Article/Selection-of-self-study-rooms.md
      - 朋友圈自我和解: ESSAY/Article/pyq-self-confident.md
      - 童年和电脑的回忆: ESSAY/Article/ChildhoodMemories.md
      - 对活着的思考: ESSAY/Article/Thinking-about-Being-Alive.md
      - 我与三北理发店: ESSAY/Article/Sanbei-BarberShop.md
      - 写博客和看博客之间的平衡: ESSAY/Article/writing-reading-blogs.md

  - 阅读:
    - READ/index.md
    - 年度合集: 
        - 2024: READ//YearlySet/2024.md
        - 2023: READ/YearlySet/2023.md
    - 特别摘录: 
        - 《小林漫画：人间烟火气》: READ/SpecialCollection/《小林漫画：人间烟火气》.md
        - 《史蒂夫·乔布斯传》: READ/SpecialCollection/《史蒂夫·乔布斯传》.md
        - 《富爸爸穷爸爸》: READ/SpecialCollection/《富爸爸穷爸爸》.md
        - 《德米安：彷徨少年时》: READ/SpecialCollection/《德米安：彷徨少年时》.md
        - 《走到人生边上:自问自答》: READ/SpecialCollection/《走到人生边上》.md
        - 《自卑与超越》: READ/SpecialCollection/Inferiority-and-transcendence.md
        - 《不负我心》: READ/SpecialCollection/bufuwoxin.md    

  - 转载:
    - REPRINT/index.md
    - 提问的智慧: REPRINT/how-to-ask-questions-the-smart-way.md
    - 演好自己的剧本: REPRINT/舞台.md
    - 我们为什么要读书: REPRINT/why-we-should-readbook.md
    - 生活在树上: REPRINT/live-in-the-tree.md
    - 持续.....: REPRINT/wait.md
  - 关于:
    - ABOUT/index.md
    - 作者信息: ABOUT/information.md
    - 网站构建: ABOUT/bulid.md
    - 支持作者: ABOUT/support.md
    
    


markdown_extensions:
  - pymdownx.arithmatex: # latex支持
      generic: true
  - attr_list # 给图片后面添加{width="300"}设置大小
  - pymdownx.emoji: # 使用emoji和icons
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      # linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.superfences # 代码块高亮插件
  - abbr # 支持Markdown文件上方自定义标题标签等
  - admonition # https://squidfunk.github.io/mkdocs-material/reference/admonitions/#inline-blocks
  - pymdownx.details # admonition需要
  - pymdownx.tabbed: # 实现在移动设备上更好的行为
      alternate_style: true 

  # - pymdownx.critic # 下面这是文本高亮、下划线、删除线需要
  - pymdownx.caret # https://squidfunk.github.io/mkdocs-material/reference/formatting/
  # - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
# [Extensions]
plugins:
  - search:
      lang: en
  - tags

extra_css: 
  - mkdocs/css/unordered-list-symbols.css # multiplt unordered list symbols
