# [Info]
site_name: 王韬安的个人网站 # 左上角标题
site_url: https://wang-taoan.github.io
site_author: 王韬安
site_description: 王韬安的个人网站

# [UI]
theme:
  name: material
  palette:
    - scheme: default # 日间模式
      primary: indigo # 主题颜色indigo red
      accent: amber # 链接等可交互元件的高亮色
      toggle:
        icon: material/brightness-7 # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: indigo #indigo red
      accent: amber
      toggle:
        icon: material/brightness-4
        name: 切换至日间模式  
  features:
    - content.tooltips
    - navigation.instant # Instant loading
    - navigation.tracking #Anchor tracking 不知道有什么用
    - navigation.tabs # 使用Tab来进行分类，就是顶层的tabs菜单
    - navigation.tabs.sticky # 锁住Tabs，向下划的时候，上面的tabs不会消失
    # - navigation.sections # 对左边菜单栏的优化，加了，文章菜单全部自动展开。不加的话有个收起的按钮
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.indexes # Tab会有一个index.md 而不是在打开Tab时打开第一篇文章
    - navigation.expand # 打开Tab时左侧目录全部展开
    - toc.follow # the sidebar is automatically scrolled so that active anchor is always visible
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - search.share # 搜索中会出现的分享按钮
    - header.autohide # 当用户滚动超过一定阈值时，留出更多的内容空间
    - navigation.footer # previous and next page of the current page的链接
  language: zh # 一些提示性的文字会变成中文
  icon:
    repo: fontawesome/brands/github
    logo: simple/datadog # logo查询https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/
edit_uri: edit/main/docs # 编辑按钮跳转的链接
## [top-right corner]
repo_url: https://github.com/Wang-Taoan/Wang-Taoan.github.io #右上角跳转的链接
repo_name: Wang-taoan.github.io # 右上角的名字
## [bottom-left corner]
copyright: Copyright &copy; 2023 王韬安 # 左下角的版权声明
## [bottom-right corner]
extra:
  homepage: https://wang-taoan.github.io/
  social: # icons
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/506537329?spm_id_from=333.337.0.0
      name: 勇敢的湍流 on Bilibili # 鼠标悬浮提示
    - icon: fontawesome/brands/github
      link: https://github.com/Wang-Taoan
      name: Wang-Taoan on Github

# [Navigtion]
nav:
  - 博客:
    - BLOG/index.md
    - C:
      - 「01」初学C语言: BLOG/C/First-learnC1.md
      - 「02」初学C语言: BLOG/C/First-learnC2.md
      -  不太明白的语法: BLOG/C/ignorantOfSyntax.md
    - JAVA:
      - 入门Java: BLOG/JAVA/begin-java.md
      - 「01」面向对象: BLOG/JAVA/01-object-oriented.md
      - 「02」面向对象: BLOG/JAVA/02-object-oriented.md
      - Java核心技术卷I笔记: BLOG/JAVA/Java-hxj1-notes.md
    - 计算机体系结构:
      - HDL下理解一台Hack计算机: BLOG/ComputerArchitecture/HDL下理解一台Hack计算机.md
      - HDL下理解一个简易的CPU: BLOG/ComputerArchitecture/HDL下理解一个简易的CPU.md
      - HDL下理解一个简易的Memory: BLOG/ComputerArchitecture/HDL下理解一个简易的Memory.md
      - HDL下理解RAM8: BLOG/ComputerArchitecture/HDL下理解RAM8.md
      - 区别RAM和ROM: BLOG/ComputerArchitecture/区分RAM和ROM.md
      - ROM32K的单位换算: BLOG/ComputerArchitecture/ROM32K的单位换算.md
      - Hack汇编语言: BLOG/ComputerArchitecture/Hack汇编语言.md    

    - 计算机基础:
      - 0 总结: BLOG/ComputerFundamentals/0总结.md
      - 1 一个内存IC的容量: BLOG/ComputerFundamentals/一个内存IC的容量.md
      - 2 硬盘和内存: BLOG/ComputerFundamentals/硬盘和内存.md
      - 3 认识一下计算机主板: BLOG/ComputerFundamentals/认识一下计算机主板.md
      - 4 认识一下虚拟机: BLOG/ComputerFundamentals/认识一下虚拟机.md
      - 5 认识一下BIOS: BLOG/ComputerFundamentals/认识一下BIOS.md
      - 6 操作系统的API差异: BLOG/ComputerFundamentals/操作系统的API差异.md
      - 7 二进制求负数: BLOG/ComputerFundamentals/二进制求负数.md
      - 8 操作系统的API差异: BLOG/ComputerFundamentals/操作系统的API差异.md
      - 9 函数调用机制的理解: BLOG/ComputerFundamentals/函数调用机制的理解.md
      - 10 初识多线程: BLOG/ComputerFundamentals/初识多线程.md
      - 11 初识中断: BLOG/ComputerFundamentals/初识中断.md
      - 12 Windows操作系统: BLOG/ComputerFundamentals/Windows操作系统.md
      - 13 DMA: BLOG/ComputerFundamentals/DMA.md
      - 14 VRAM和GPU: BLOG/ComputerFundamentals/VRAM和GPU.md
      
    - Markdown:
      - Markdown文件命名规则: BLOG/Markdown/name-regulation.md
      - Markdown使用语法: BLOG/Markdown/markdown-grammar.md
      #- 文章3:<相对路径>
    - 生活中的计算机:
      - U盘-SSD存储大小缩水: BLOG/CsInTheLife/SSD-in-life.md
      - 运行商所谓的宽带: BLOG/CsInTheLife/broadband.md
      - 字节和字符的区别: BLOG/CsInTheLife/characters-and-bytes.md
      - HTTP与HTTPS的区别: BLOG/CsInTheLife/HTTP-HTTPS.md
    - 浏览器扩展程序:
      - Tampermonkey: BLOG/BrowserExtension/Tampermonkey插件安装和使用.md
    - 其他:
      - 如何下载音乐: BLOG/Other/download-music.md
      #- 文章2:<相对路径>
      #- 文章3:<相对路径>
    #- MacOS
      #- 文章1:<相对路径>
      #- 文章2:<相对路径>
      #- 文章3:<相对路径>
  - 学习:
    - LEARNING/index.md
    - 如何去学好一门课: LEARNING/how-to-learn-a-course-well.md
    - 目标:
      - JAVA学习目标【弃】: LEARNING/Target/java-target.md
      - 大二下日常学习流: LEARNING/Daily-learning-stream.md
      - 本学期目标: LEARNING/Target/target-2023.md
    #- More

  - 喜欢的东西:
    - LIKETHINGS/index.md
    - 喜欢的歌: LIKETHINGS/songs.md
    - 三国杀人物台词: LIKETHINGS/三国杀人物台词.md
    - 诗歌序: LIKETHINGS/诗歌序.md
    #- LIKE1
      #- 文章1:<相对路径>
      #- 文章2:<相对路径>
      #- 文章3:<相对路径>
   
  - 生活: 
    - LIFE/index.md
    - 随笔:
      - 前言: LIFE/Jottings/随笔前言.md
      - 2023-03: LIFE/Jottings/2023-03.md
      - 2023-02: LIFE/Jottings/2023-02.md
      - 2023-01: LIFE/Jottings/2023-01.md
      - 2022-12: LIFE/Jottings/2022-12.md
      - 2022-11: LIFE/Jottings/2022-11.md
      #- 文章3:<相对路径>
    - 文章:
      - 对活着的思考: LIFE/Article/对活着的思考.md
      - 我与三北理发店: LIFE/Article/我与三北理发店.md
      - 写博客和看博客之间的平衡: LIFE/Article/写博客和看博客之间的平衡.md
    - 阅读:
      - 2023-03: LIFE/Read/2023-03book.md
      - 2023-02: LIFE/Read/2023-02book.md
      - 读后有感:
        - 《自卑与超越》: LIFE/Read/Feelings-After-Read/Inferiority-and-transcendence.md

    
  - 转载:
    - REPRINT/index.md
    - 提问的智慧: REPRINT/how-to-ask-questions-the-smart-way.md
    - 演好自己的剧本: REPRINT/舞台.md
    - 我们为什么要读书: REPRINT/why-we-should-readbook.md
    - 生活在树上: REPRINT/live-in-the-tree.md
    - 持续.....: REPRINT/wait.md
  - 关于:
    - ABOUT/index.md
    - 作者信息: ABOUT/information.md
    - 网站构建: ABOUT/bulid.md
    - 支持作者: ABOUT/support.md
    
    


markdown_extensions:
  - pymdownx.arithmatex: # latex支持
      generic: true
  - attr_list # 给图片后面添加{width="300"}设置大小
  - pymdownx.emoji: # 使用emoji和icons
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      # linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.superfences # 代码块高亮插件
  - abbr # 支持Markdown文件上方自定义标题标签等
  - admonition # https://squidfunk.github.io/mkdocs-material/reference/admonitions/#inline-blocks
  - pymdownx.details # admonition需要

  # - pymdownx.critic # 下面这是文本高亮、下划线、删除线需要
  - pymdownx.caret # https://squidfunk.github.io/mkdocs-material/reference/formatting/
  # - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
# [Extensions]
plugins:
  - search:
      lang: en
  - tags
  # - git-revision-date-localized: # 不知道怎么用不了
     # enable_creation_date: true #https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#document-dates
      # type: date
extra_css: 
  - mkdocs/css/unordered-list-symbols.css # multiplt unordered list symbols
